const sampleNames = [
    { name: "Alice Johnson" },
    { name: "Abhinav Agnihotri" },
    { name: "Yuki" },
    { name: "Lara Croft" },
    { name: "Pablo" },
    { name: "Olga Ivanova" },
    { name: "Chen Wei" },
    { name: "Aisha" },
    { name: "Jack" },
    { name: "Mia Rodriguez" },
    { name: "Nina Patel" },
    { name: "Omar" },
    { name: "Paulo Sousa" },
    { name: "Quinn Murphy" },
    { name: "Ravi" },
    { name: "Sakura Tanaka" },
    { name: "Timur" },
    { name: "Ursula" },
    { name: "Vinh" },
    { name: "Wang Lei" },
    { name: "Ximena Gonzalez" },
    { name: "Youssef" },
    { name: "Zara Ahmed" },
    { name: "Aaron Smith" },
    { name: "Bianca" },
    { name: "Carlos Mendez" },
    { name: "Danielle" },
    { name: "Elena Petrova" },
    { name: "Fatima" },
    { name: "George Brown" },
    { name: "Hana Kim" },
    { name: "Isabella" },
    { name: "Jose Martinez" },
    { name: "Khalid" },
    { name: "Linda" },
    { name: "Mateo Garcia" },
    { name: "Natalie" },
    { name: "Oscar" },
    { name: "Priya" },
    { name: "Rajesh" },
    { name: "Sophia" },
    { name: "Tariq" },
    { name: "Uma" },
    { name: "Victor" },
    { name: "Wendy" },
    { name: "Xavier" },
    { name: "Yara" },
    { name: "Zane" },
    { name: "Anton" },
    { name: "Barbara" },
    { name: "Carmen" },
    { name: "Diego" },
    { name: "Eva" },
    { name: "Felix" },
    { name: "Giselle" },
    { name: "Henry" },
    { name: "Ivy" },
    { name: "James" },
    { name: "Katherine" },
    { name: "Liam" },
    { name: "Maria" },
    { name: "Nathan" },
    { name: "Olivia" },
    { name: "Peter" },
    { name: "Quincy" },
    { name: "Rose" },
    { name: "Samuel" },
    { name: "Tina" },
    { name: "Ulysses" },
    { name: "Vera" },
    { name: "Will" },
    { name: "Xena" },
    { name: "Yvonne" },
    { name: "Zachary" },
    { name: "Aiden" },
    { name: "Bella" },
    { name: "Charlie" },
    { name: "Diana" },
    { name: "Edward" },
    { name: "Fiona" },
    { name: "Walter" },
    { name: "Gavin" },
    { name: "Holly" },
    { name: "Ian" },
    { name: "Julia" },
    { name: "Kyle" },
    { name: "Laura" },
    { name: "Mason" },
    { name: "Nora" },
    { name: "Owen" },
    { name: "Paige" },
    { name: "Ryan" },
    { name: "Sarah" },
    { name: "Tom" },
    { name: "Una" },
    { name: "Vanessa" },
    { name: "Walter" },
    { name: "Xander" },
    { name: "Yolanda" },
    { name: "Zeke" }
];

module.exports=sampleNames;