const sampleReviews = [
    { comment: "Amazing experience! The beaches were beautiful and the food was fantastic.", rating: 5 },
    { comment: "The hotel was decent but the service could have been better. Not worth the high price.", rating: 3 },
    { comment: "Terrible experience. The flight was delayed, and the hotel was dirty. Would not recommend.", rating: 1 },
    { comment: "Had a great time! The guided tours were very informative and well-organized.", rating: 4 },
    { comment: "Average trip. Some attractions were interesting, but the overall experience was just okay.", rating: 2 },
    { comment: "Wonderful vacation! The staff was very friendly and helpful.", rating: 5 },
    { comment: "Not satisfied with the service. The room was not clean.", rating: 2 },
    { comment: "Loved every moment of it! Will definitely visit again.", rating: 5 },
    { comment: "It was an okay trip. Some parts were enjoyable.", rating: 3 },
    { comment: "The worst trip ever. Everything was disorganized.", rating: 1 },
    { comment: "Great location and excellent facilities. Had a memorable time.", rating: 5 },
    { comment: "The food was not good, and the room was noisy.", rating: 2 },
    { comment: "The trip was fantastic! The scenery was breathtaking.", rating: 5 },
    { comment: "Service was average, but the place was beautiful.", rating: 3 },
    { comment: "Really bad experience. The hotel did not meet our expectations.", rating: 1 },
    { comment: "We enjoyed our stay. The activities were fun and diverse.", rating: 4 },
    { comment: "The trip was below average. Not worth the money.", rating: 2 },
    { comment: "Incredible trip! Everything was perfect.", rating: 5 },
    { comment: "The service was mediocre, and the room was outdated.", rating: 3 },
    { comment: "A total disaster. Nothing went right during our trip.", rating: 1 },
    { comment: "The guided tours were excellent and very educational.", rating: 4 },
    { comment: "Overall, it was an average experience.", rating: 2 },
    { comment: "Fantastic destination! We had a wonderful time.", rating: 5 },
    { comment: "The hotel was okay but could use some improvements.", rating: 3 },
    { comment: "Extremely disappointed with the trip. Poor management.", rating: 1 },
    { comment: "Lovely trip! The nature walks were a highlight.", rating: 4 },
    { comment: "Just an average experience. Nothing special.", rating: 2 },
    { comment: "The best vacation we've ever had. Highly recommend!", rating: 5 },
    { comment: "The place was nice, but the food was not great.", rating: 3 },
    { comment: "Horrible trip. Everything was a mess.", rating: 1 },
    { comment: "We had a good time. The weather was perfect.", rating: 4 },
    { comment: "An okay trip. Could have been better.", rating: 2 },
    { comment: "Absolutely amazing! Exceeded all our expectations.", rating: 5 },
    { comment: "The service was not up to the mark.", rating: 3 },
    { comment: "Never again. The worst experience ever.", rating: 1 },
    { comment: "Beautiful location and great hospitality.", rating: 4 },
    { comment: "The trip was underwhelming. Not worth the cost.", rating: 2 },
    { comment: "Exceptional service and beautiful surroundings.", rating: 5 },
    { comment: "The room was okay, but the amenities were lacking.", rating: 3 },
    { comment: "A nightmare trip. Nothing went as planned.", rating: 1 },
    { comment: "Good trip. Enjoyed the activities and the ambiance.", rating: 4 },
    { comment: "It was just a so-so experience.", rating: 2 },
    { comment: "Highly recommend this destination. Amazing experience.", rating: 5 },
    { comment: "The hotel needs improvement, especially in cleanliness.", rating: 3 },
    { comment: "A terrible experience. Very dissatisfied.", rating: 1 },
    { comment: "Wonderful staff and beautiful location.", rating: 4 },
    { comment: "Not a great experience. Expected more.", rating: 2 },
    { comment: "Best trip ever! Everything was perfect.", rating: 5 },
    { comment: "The place was good, but the service was lacking.", rating: 3 },
    { comment: "Really bad experience. Would not recommend.", rating: 1 },
    { comment: "We had an enjoyable time. The excursions were fun.", rating: 4 },
    { comment: "An average trip. Some good, some bad.", rating: 2 },
    { comment: "Fantastic trip! Loved every moment.", rating: 5 },
    { comment: "The service was okay, but the room was noisy.", rating: 3 },
    { comment: "Disappointing trip. Not worth the hype.", rating: 1 },
    { comment: "The guided tours were excellent.", rating: 4 },
    { comment: "An okay trip. Could have been better.", rating: 2 },
    { comment: "Overall, it was just okay.", rating: 2 },
    { comment: "Amazing experience! Will definitely come back.", rating: 5 },
    { comment: "The hotel was decent but needs improvements.", rating: 3 },
    { comment: "Terrible experience. Nothing was good.", rating: 1 },
    { comment: "Great trip! The staff was very helpful.", rating: 4 },
    { comment: "An okay trip. Could have been better.", rating: 2 },
    { comment: "Had a fantastic time! Everything was great.", rating: 5 },
    { comment: "Service was average, but the location was beautiful.", rating: 3 },
    { comment: "Worst trip ever. Very disorganized.", rating: 1 },
    { comment: "We enjoyed our stay. The activities were fun.", rating: 4 },
    { comment: "The trip was below average.", rating: 2 },
    { comment: "Incredible trip! Highly recommend.", rating: 5 },
    { comment: "The service was mediocre.", rating: 3 },
    { comment: "A total disaster. Would not recommend.", rating: 1 },
    { comment: "The guided tours were very educational.", rating: 4 },
    { comment: "Overall, it was an average experience.", rating: 2 },
    { comment: "Fantastic destination! Had a great time.", rating: 5 },
    { comment: "The place was nice, but the food was bad.", rating: 3 },
    { comment: "The hotel was okay but could improve.", rating: 3 },
    { comment: "Extremely disappointed with the trip.", rating: 1 },
    { comment: "Lovely trip! The nature walks were amazing.", rating: 4 },
    { comment: "Just an average experience.", rating: 2 },
    { comment: "The best vacation ever. Highly recommend!", rating: 5 },
    { comment: "The place was nice, but the food was bad.", rating: 3 },
    { comment: "Horrible trip. Everything was a mess.", rating: 1 },
    { comment: "We had a good time. The weather was great.", rating: 4 },
    { comment: "Good trip. Enjoyed the activities.", rating: 4 },
    { comment: "It was just a so-so experience.", rating: 2 },
    { comment: "An okay trip. Nothing special.", rating: 2 },
    { comment: "Absolutely amazing! Highly recommend.", rating: 5 },
    { comment: "The service was not great.", rating: 3 },
    { comment: "Never again. The worst trip ever.", rating: 1 },
    { comment: "Wonderful staff and beautiful location.", rating: 4 },
    { comment: "Beautiful location and great service.", rating: 4 },
    { comment: "The trip was underwhelming.", rating: 2 },
    { comment: "Exceptional service and beautiful place.", rating: 5 },
    { comment: "The room was okay, but the amenities were lacking.", rating: 3 },
    { comment: "A nightmare trip. Nothing went right.", rating: 1 },
    { comment: "Good trip. Enjoyed the activities.", rating: 4 },
    { comment: "It was just a so-so experience.", rating: 2 },
    { comment: "Highly recommend this destination. Amazing trip.", rating: 5 },
    { comment: "The hotel needs improvement.", rating: 3 },
    { comment: "A terrible experience.", rating: 1 }
];

module.exports=sampleReviews;
